# Configuration for Railway Nixpacks
# Ref: https://nixpacks.com/docs/providers/php

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-gd"]

[phases.build]
cmds = [
    "npm install",
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php-fpm -D && nginx -g 'daemon off;'"
